name: Test

on:
  pull_request:
    branches: [main] # Must match the name of your repo's default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Use MySql"
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "8.0"
          mysql root password: root

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=root --silent; do
            sleep 1
          done

      - name: Configure Mysql
        run: |
          mysql -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';" -h 127.0.0.1 -u root -proot
          mysql -e "flush privileges;" -h 127.0.0.1 -u root -proot

      - name: Run tests
        run: npm test
        env:
          DEV_HOST: 127.0.0.1
          DEV_USER: root
          DEV_PASSWORD: root
